apiVersion: eksctl.io/v1alpha5

kind: ClusterConfig

metadata:
  name: gj2026-eks-cluster
  region: ap-northeast-2
  version: "1.35"

vpc:
  id: VPC_ID
  subnets:
    private:
      ap-northeast-2a: { id: PRIVATE_A }
      ap-northeast-2b: { id: PRIVATE_B }
  clusterEndpoints:
    privateAccess: true
    publicAccess: true

secretsEncryption:
  keyARN: EKS_KEY_ARN

addonsConfig:
  autoApplyPodIdentityAssociations: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent

iam:
  withOIDC: false

managedNodeGroups:
  - name: gj2026-eks-addon-nodegroup
    amiFamily: Bottlerocket
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true
    subnets:
      - PRIVATE_A
      - PRIVATE_B
    labels:
      role: addon
    tags:
      Name: gj2026-eks-addon-node
    propagateASGTags: true
    volumeSize: 20
    volumeType: gp3
    bottlerocket:
      settings:
        bootstrap-containers:
          set-hostname:
            source: SET_HOSTNAME_IMAGE
            mode: always
            essential: false
            user-data: YWRkb24=
  - name: gj2026-eks-app-nodegroup
    amiFamily: Bottlerocket
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 2
    maxSize: 2
    privateNetworking: true
    subnets:
      - PRIVATE_A
      - PRIVATE_B
    labels:
      role: app
    taints:
      - key: dedicated
        value: app
        effect: NoSchedule
    tags:
      Name: gj2026-eks-app-node
    propagateASGTags: true
    volumeSize: 20
    volumeType: gp3
    bottlerocket:
      settings:
        bootstrap-containers:
          set-hostname:
            source: SET_HOSTNAME_IMAGE
            mode: always
            essential: false
            user-data: YXBw
