apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: apdev
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:

      containers:
        - name: user
          image: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/apdev-user:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
          env:
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: apdev-db-config
                  key: MYSQL_USER
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: apdev-db-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: apdev-db-config
                  key: MYSQL_PORT
            - name: MYSQL_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: apdev-db-config
                  key: MYSQL_DBNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apdev-db-secret
                  key: MYSQL_PASSWORD
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep 20"]
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: user-svc
  namespace: apdev
spec:
  type: ClusterIP
  selector:
    app: user
  ports:
    - port: 80
      targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-hpa
  namespace: apdev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-deploy
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
    scaleDown:
      stabilizationWindowSeconds: 120