# 3. Log Collector - OpenTelemetry Collector (DaemonSet, monitoring NS)
# helm install o11y-otel open-telemetry/opentelemetry-collector -n monitoring -f otel-values.yaml
mode: daemonset
fullnameOverride: o11y-otel

image:
  repository: otel/opentelemetry-collector-contrib

presets:
  # filelog receiver -> /var/log/pods/*/*/*.log
  logsCollection:
    enabled: true
    includeCollectorLogs: false
  # k8sattributes processor (namespace/pod 메타데이터 enrichment)
  kubernetesAttributes:
    enabled: true

config:
  exporters:
    otlphttp/loki:
      logs_endpoint: http://o11y-loki.monitoring.svc.cluster.local:3100/otlp/v1/logs
      tls:
        insecure: true
  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [k8sattributes, batch]
        exporters: [otlphttp/loki]
