apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: apdev-eks-cluster
  region: ap-northeast-2
  version: "1.36"

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true
    - metadata:
        name: cluster-autoscaler
        namespace: kube-system
      wellKnownPolicies:
        autoScaler: true

vpc:
  id: "VPC_ID"
  subnets:
    public:
      ap-northeast-2a: { id: "PUBLIC_A" }
      ap-northeast-2c: { id: "PUBLIC_C" }
    private:
      ap-northeast-2a: { id: "PRIVATE_A" }
      ap-northeast-2c: { id: "PRIVATE_C" }

managedNodeGroups:
  - name: apdev-eks-node
    instanceName: apdev-eks-node-instance
    instanceType: t3.medium
    amiFamily: AmazonLinux2023
    desiredCapacity: 2
    minSize: 2
    maxSize: 10
    volumeSize: 30
    privateNetworking: true
    subnets:
      - "PRIVATE_A"
      - "PRIVATE_C"
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/apdev-eks-cluster: "owned"
    propagateASGTags: true

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: metrics-server