apiVersion: v1
kind: ConfigMap
metadata:
  name: apdev-db-config
  namespace: apdev
data:
  MYSQL_USER: "admin"
  MYSQL_HOST: "apdev-rds-instance.chs8yo2w68v0.ap-northeast-2.rds.amazonaws.com"
  MYSQL_PORT: "3306"
  MYSQL_DBNAME: "dev"