apiVersion: v1
kind: ConfigMap
metadata:
  name: apdev-db-config
  namespace: apdev
data:
  MYSQL_USER: admin
  MYSQL_HOST: <MYSQL_RDS_ENDPOINT>
  MYSQL_PORT: "4000"
  MYSQL_DBNAME: dev
  S3_BUCKET: <S3_BUCKET_NAME>